CREATE DATABASE PizzaRestaurantDB
USE PizzaRestaurantDB


-- Exploring and Cleaning Data
SELECT *
FROM [dbo].[order$]


SELECT *
FROM [dbo].[order$]
WHERE [total_price] = 0

DELETE 
FROM [dbo].[order$]
WHERE [total_price] = 0

SELECT *
FROM [dbo].[order$]
WHERE [total_price] IS NULL

DELETE 
FROM [dbo].[order$]
WHERE [total_price] IS NULL
-- almost all the other data is clean
-- since data was generated by a python program


--Queries for Dashboard 1


SELECT COUNT([order_id]) AS 'TOTAL ORDER',
SUM([total_price]) AS 'TOTAL SALES', 
AVG([total_price]) AS 'AVERAGE ORDER VALUE'
FROM [dbo].[order$]



SELECT COUNT([item_id(fk)]) AS 'TOTAL ITEMS SOLD'
FROM [dbo].[OrderItem$]



-- SALES BY CATEGORY
-- get total quantity sold from orderItem
-- get the price of individual Item from Item table
-- multiply both

SELECT 
oi.[item_id(fk)],
COUNT(oi.[item_id(fk)]) AS 'TTL_QTY',
SUM(i.[price]) AS 'Sales BY Category'
FROM [dbo].[OrderItem$] AS oi
JOIN [dbo].[Item$] AS i
ON oi.[item_id(fk)]=i.[item_id]
GROUP BY oi.[item_id(fk)]
ORDER BY 3 DESC


SELECT [order_id], [created_at], [date]
FROM [dbo].[order$]
ORDER BY [created_at], [date] ASC 


SELECT * FROM [dbo].[order$]